### ISSUE TITLE
TODO for v0.1.0

### ISSUE THREAD

**Issue by Tatskaari** [please-build/puku#1]
- [ ] Update the visibility for targets as we depend on them
- [x] Parse the config and 
     - [x] Load the build file names
     - [x] Check if we need to add the subinclude or if it's pre-loaded
     - [x] Set the working directory to the Please project root
- [x] Handle custom kinds - these should be configured as lib, test or binary equivalents and have provided deps that we don't need to add as deps to the rule. 
- [ ] Add watch mode
- [x] Support wildcards on the command line (we'll need to generate these in the right order) 
- [x] Have a no-op mode that outputs a patch that we can use for `arc lint` etc. 
- [ ] README 
- [x] Known dependencies (if needed? are custom kinds enough? Can we use `plz query` to find them?)
